String about =
    "As a skilled freelance Flutter developer, I specialize in creating dynamic and responsive mobile applications that meet client needs. I offer competitive pricing, providing high-quality app development at rates lower than the current market standards. \n\nWith my expertise, I can turn your ideas into reality—if you can imagine it, I can code it.\n\nFrom integrating complex functionalities like payment gateways and real-time communication to crafting custom UI/UX designs, I bring your vision to life with clean, efficient code. Whether it's developing from scratch or optimizing existing apps, I am dedicated to delivering exceptional results that exceed expectations";
String outshadeExperience =
    " I specialized in bug fixing and optimization. Notably, I resolved a critical notification bug, ensuring smooth and timely alerts for users. Additionally, I worked extensively with BLoC state management, enhancing the efficiency and maintainability of the applications. My contributions have consistently improved app performance and user experience.";
String aypexExperience =
    "At Aypex Pvt Ltd, I have been actively contributing as a Flutter developer since October 2023. My key achievements include implementing the Google Maps API to enable users to search for nearby available teachers, and developing a one-to-one chatting system using Firebase for real-time communication. I also integrated RazorPay for seamless wallet transactions and utilized BLoC state management to ensure a smooth and responsive user experience. Additionally, I optimized the Firebase database by simplifying data structures, resulting in a more efficient application. The app has been successfully published on the Play Store, demonstrating my commitment to delivering high-quality, user-centric solutions";
String c4dexp =
    "As a Flutter Developer at Connect 4 Digital India, I have been working onsite since March 2024. I developed and integrated a custom solution using the WooCommerce REST API, enhancing e-commerce functionalities within a Flutter application while leveraging BLoC state management for an improved user experience. I also added the STRIPE SDK as a payment gateway to facilitate secure transactions.Additionally, I developed and integrated WebRTC for peer-to-peer audio and video communication, ensuring secure and reliable data transmission using ICE, STUN, and TURN servers, and handled signaling via WebSockets. My role also involved developing and maintaining mobile apps using Flutter and Figma, as well as designing a Firebase database to streamline CRUD operations, making the application more efficient and user-friendly";
String instaCloneDec =
    "I developed a full-stack Instagram clone, a platform that allows users to share photos, follow others, like, comment on posts, and upload content. The project involved implementing user authentication and authorization using FireAuth Technology, and designing a frontend interface that closely mimics Instagram's user experience. I utilized Firebase as the database system to efficiently store and access user data, posts, and interactions. The project was built using Flutter, Firebase, and Dart.";
String webrtcdec =
    "I developed a multiuser video call application utilizing WebRTC for real-time communication, Firebase for backend services, and Flutter for the frontend interface. This project enabled seamless video conferencing between multiple users, ensuring secure and reliable connections. The integration of WebRTC provided low-latency and high-quality video communication, while Firebase handled the signaling and data management to maintain a smooth user experience";
