// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbsuZ6GMrAOX7dZNqwlgftpsOySXSg8g',
    appId: '1:1099425872243:web:287bc84b1d4fdc36af2d06',
    messagingSenderId: '1099425872243',
    projectId: 'port-fol-io',
    authDomain: 'port-fol-io.firebaseapp.com',
    storageBucket: 'port-fol-io.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJuH7IBz37_xHzMhJAWdb6N5i3VA7VCKQ',
    appId: '1:1099425872243:android:2ae20ceebdb81485af2d06',
    messagingSenderId: '1099425872243',
    projectId: 'port-fol-io',
    storageBucket: 'port-fol-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5U9YDIQegTvYLZrI6Nfe2x9sKSRb6Rw',
    appId: '1:1099425872243:ios:00be5e1a1af9c5a2af2d06',
    messagingSenderId: '1099425872243',
    projectId: 'port-fol-io',
    storageBucket: 'port-fol-io.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ5U9YDIQegTvYLZrI6Nfe2x9sKSRb6Rw',
    appId: '1:1099425872243:ios:22f6bc77ec84ae3daf2d06',
    messagingSenderId: '1099425872243',
    projectId: 'port-fol-io',
    storageBucket: 'port-fol-io.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
